# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiroshi" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "c3136b435ed9613e08adf6c4c22850fdf6dff2e7b2ab09aaa6cc0e66c1323c29"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98081ca2808e62fca2ab99fbc280f58e5ac6d6556f276e8c4db86591859c8852"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "146b8fb36f85bd3d81ecf1436bb7690c1e5c535edbff178f5d15db5db1186695"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0c9d434cb659b1aacf7fa6007145bc020b764f40d23561d33ebdfcee9407ce3"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kiroshi"
  desc "GitHub pull request dashboard for the terminal"
  homepage "https://github.com/ajardin/kiroshi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiroshi"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiroshi"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `kiroshi -init` to create your configuration (GitHub token, search query).
  EOS
end
