# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiroshi" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "6aee5044da942560d893e0318d3c70a86a370e1802678b585a827937d9075a28"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "737d767ad860a8d27c5a4a80cb855ca4775273cb5742857188b5275f9ab6f135"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83d4cc9985988dbfad89721a7069c71789a708e4401c8facd933d1b1ac28d115"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a6f6641aed76e1172070d81f26fffb207ea4d255f0c89a0f429aed3425fdb16"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kiroshi"
  desc "GitHub pull request dashboard for the terminal"
  homepage "https://github.com/ajardin/kiroshi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiroshi"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiroshi"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `kiroshi -init` to create your configuration (GitHub token, search query).
  EOS
end
