# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiroshi" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "89f0ef1c2bece4733568e3cd6238df04b7f3f9789d996c409ae212eca0fe0635"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dab3e1fb7f66d258583849327db60de11d2a0fccdecc5e204a6e5f823d40a471"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "406f0ed3c5bf64e3071dcee206cfec47dafdadfc6fa895ef5c36c78a02364e57"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "37744e8f83a3b6aa37ec01a18c635e4b9c32b22eb0ffc7b8f2846da9256dd2ca"
      url "https://github.com/ajardin/kiroshi/releases/download/v#{version}/kiroshi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kiroshi"
  desc "GitHub pull request dashboard for the terminal"
  homepage "https://github.com/ajardin/kiroshi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiroshi"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiroshi"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `kiroshi -init` to create your configuration (GitHub token, search query).
  EOS
end
